# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'ILTestingDemo' do
    
pod 'PromiseKit'

end

target 'ILTestingDemoTests' do

pod 'Quick'
pod 'Nimble'
pod 'PromiseKit'

end

target 'ILTestingDemoUITests' do

pod 'Quick'
pod 'Nimble'

end

